name: Build and Deploy
on:   
  push:
  schedule:
    - cron: '0 1 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
 
      - name: Cargo Cache
        id: cargo-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get a-s repository
        run: |
          git init .
          git remote add origin https://github.com/mozilla/application-services.git

      - name: Install mdbook dependencies
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: cargo install mdbook mdbook-mermaid mdbook-open-on-gh   
      
      - name: Create Developer Docs
        run: |
          git pull origin SYNC-2121-steal-this-book
          ./tools/build-book.sh



      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/docs # The folder the action should deploy.
