name: Build and Deploy
on:   
  push:
  schedule:
    - cron: '0 1 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
            
      - name: Create Dev Docs
        run: |
          git init .
          git remote add origin https://github.com/mozilla/application-services.git
          cargo install mdbook mdbook-mermaid mdbook-open-on-gh
          git pull origin SYNC-2121-steal-this-book
          ./tools/build-book.sh

      - name: Build Dependencies and Generate Rust Docs
        run: |
          git submodule init
          git submodule update --recursive
          git clone https://chromium.googlesource.com/external/gyp.git tools/gyp
          cd tools/gyp
          sudo python setup.py install
          cd ../..
          sudo apt-get install ninja-build zlib1g-dev tclsh python3.6
          export SQLCIPHER_LIB_DIR=/home/runner/work/jdragojevic/action-docs/libs/desktop/linux-x86-64/sqlcipher/lib
          export SQLCIPHER_INCLUDE_DIR=/home/runner/work/jdragojevic/action-docs/libs/desktop/linux-x86-64/sqlcipher/include
          export NSS_DIR=/home/runner/work/jdragojevic/action-docs/libs/desktop/linux-x86-64/nss
          export NSS_STATIC=1
          bash ./libs/verify-desktop-environment.sh
          cargo doc --no-deps --document-private-items
          git log -n 1 --pretty=format:"%H" > target/doc/index.html
          mv -f target/doc build/docs/rust-docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/docs # The folder the action should deploy.
